// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class Campus
    {
        public Campus()
        {
            Degree = new HashSet<Degree>();
            School = new HashSet<School>();
        }
        [Key]
        public int id { get; set; }
        public string campusName { get; set; }

        public virtual ICollection<Degree> Degree { get; set; }
        public virtual ICollection<School> School { get; set; }
    }
}