// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class Canton
    {
        public Canton()
        {
            District = new HashSet<District>();
            StudentIntegratec = new HashSet<StudentIntegratec>();
        }

        [Key]
        public int cantonId { get; set; }
        public string cantonName { get; set; }
        public int provinceId { get; set; }

        public virtual Province province { get; set; }
        public virtual ICollection<District> District { get; set; }
        public virtual ICollection<StudentIntegratec> StudentIntegratec { get; set; }
    }
}