// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Model
{
    public class Canton
    {
        [Key]
        [Column("cantonId")]
        public int CantonId { get; set; }

        [Required]
        [Column("cantonName")]
        public string CantonName { get; set; }

        [ForeignKey("Province")]
        [Column("provinceId")]
        public int ProvinceId { get; set; }
        public virtual Province Province { get; set; }
    }
}