// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class District
    {
        public District()
        {
            StudentIntegratec = new HashSet<StudentIntegratec>();
        }
        [Key]
        public int districtId { get; set; }
        public string districtName { get; set; }
        public int cantonId { get; set; }

        public virtual Canton canton { get; set; }
        public virtual ICollection<StudentIntegratec> StudentIntegratec { get; set; }
    }
}