// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Model
{
    public class District
    {
        [Key]
        [Column("districtId")]
        public int DistrictId { get; set; }

        [Required]
        [Column("districtName")]
        public string DistrictName { get; set; }

        [ForeignKey("Canton")]
        [Column("cantonId")]
        public int CantonId { get; set; }
        public virtual Canton Canton { get; set; }
    }
}