// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class Liking
    {
        public Liking()
        {
            email = new HashSet<Godchild>();
            mentorEmail = new HashSet<Mentor>();
        }
        [Key]
        public int likingId { get; set; }
        public string likingName { get; set; }

        public virtual ICollection<Godchild> email { get; set; }
        public virtual ICollection<Mentor> mentorEmail { get; set; }
    }
}