// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class Mentor
    {
        public Mentor()
        {
            liking = new HashSet<Liking>();
        }
        [Key]
        public string email { get; set; }

        public virtual StudentIntegratec emailNavigation { get; set; }

        public virtual ICollection<Liking> liking { get; set; }
    }
}