// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;

namespace LayoutTemplateWebApp.Model
{
    public partial class Organization
    {
        [Key]
        public string email { get; set; }
        public int? degreeId { get; set; }
        public string organizationPassword { get; set; }
        public string organizationName { get; set; }
        public int typeId { get; set; }
        public bool? isCouncil { get; set; }

        public virtual Degree degree { get; set; }
        public virtual OrganizationType type { get; set; }
    }
}