// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class Person
    {
        public Person()
        {
            PersonXApplicationRole = new HashSet<PersonXApplicationRole>();
        }
        [Key]
        public string email { get; set; }
        public string personPassword { get; set; }
        public int id { get; set; }
        public string personName { get; set; }
        public string firstLastName { get; set; }
        public string secondLastName { get; set; }
        public int? debt { get; set; }

        public virtual AdminIntegratec AdminIntegratec { get; set; }
        public virtual StudentIntegratec StudentIntegratec { get; set; }
        public virtual ICollection<PersonXApplicationRole> PersonXApplicationRole { get; set; }
    }
}