// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Model
{
    public partial class PersonXApplicationRole
    {
        [NotMapped]
        public List<string> Emails { get; set; }

        public int applicationRoleId { get; set; }

        [ForeignKey("email")]
        public virtual Person emailNavigation { get; set; }
    }
}