// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Model
{
    public class Province
    {
        [Key]
        [Column("provinceId")]
        public int ProvinceId { get; set; }

        [Required]
        [Column("provinceName")]
        public string ProvinceName { get; set; }
    }
}