// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class School
    {
        [Key]
        public int id { get; set; }
        public string schoolName { get; set; }
        public int campusId { get; set; }

        public virtual Campus campus { get; set; }
    }
}