// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Model
{
    public class StudentIntegratec
    {
        [Key]
        [Column("email")]
        public string Email { get; set; }

        [Column("numContact")]
        public string NumContact { get; set; }

        [ForeignKey("Province")]
        [Column("provinceId")]
        public int? ProvinceId { get; set; }
        public virtual Province Province { get; set; }

        [ForeignKey("Canton")]
        [Column("cantonId")]
        public int? CantonId { get; set; }
        public virtual Canton Canton { get; set; }

        [ForeignKey("District")]
        [Column("districtId")]
        public int? DistrictId { get; set; }
        public virtual District District { get; set; }

        [NotMapped]
        public UserAPIModel Person { get; set; }

    }
}