// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LayoutTemplateWebApp.Model
{
    public partial class StudentIntegratec
    {
        [Key]
        public string email { get; set; }
        public string numContact { get; set; }
        public int? provinceId { get; set; }
        public int? cantonId { get; set; }
        public int? districtId { get; set; }

        public virtual Canton canton { get; set; }
        public virtual District district { get; set; }
        public virtual Person emailNavigation { get; set; }
        public virtual Province province { get; set; }
        public virtual Godchild Godchild { get; set; }
        public virtual Mentor Mentor { get; set; }
    }
}